### ISSUE TITLE
Provide contrast ratio function

### ISSUE THREAD

**Issue by hadley** [EmilHvitfeldt/prismatic#34] opened 2024-05-08 22:40 UTC
like `colorspace::contrast_ratio("#dc3545", "#f8f9fa")`

Not exactly related to the core purpose of the package, but when generating colours it is very useful to be able to check their accessibility.

**Comment by EmilHvitfeldt** [comment] 2024-05-08 23:34
Are you thinking contrast_ratio()? 😁
https://emilhvitfeldt.github.io/prismatic/reference/contrast_ratio.html

Also have best_contrast() helper which is vectorized by first argument
https://emilhvitfeldt.github.io/prismatic/reference/best_contrast.html

**Comment by EmilHvitfeldt** [comment] 2024-05-08 23:36
Closed as duplicate of https://github.com/EmilHvitfeldt/prismatic/issues/18

**Closed** 2024-05-08 23:36 UTC

**Comment by hadley** [comment] 2024-05-09 16:59
I can't believe I already filed this issue and you fixed it 😆
